version: '3'
services:
  pg:
    image: postgres  # 基础镜像
    container_name: "fund_postgres"  # 容器名称
    volumes:
      - pg-data:/var/lib/postgresql/data  # 数据卷挂载
    environment:
      - POSTGRES_DB=fund  # 默认数据库名
      - POSTGRES_USER=postgres  # 默认数据库用户
      - POSTGRES_PASSWORD=123456  # 默认数据库密码

  mongo:
    image: mongo
    container_name: "fund_mongo"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: "fund_redis"
    volumes:
      - redis-data:/data

  web_go:
    container_name: "fund_go"
    build: .  # Dockerfile文件目录
    ports:  # 暴露端口
      - "10888:10888"
    links:
      - pg
      - redis
      - mongo
    depends_on:
      - web_py
      - pg
      - redis
      - mongo

  web_py:
    container_name: "fund_py"
    build: C:/Users/lucario/PycharmProjects/fund/  # Dockerfile文件目录
    command: python server.py  # 运行容器时运行命令
    ports:
      - "5000:5000"
    volumes:
      - kline-data:/code/common/kline
    links:
      - pg
      - mongo
    depends_on:
      - pg
      - mongo

volumes: # 数据卷
  pg-data:
  mongo-data:
  redis-data:
  kline-data: