version: '2'
services:
  pg:
    image: postgres  # 基础镜像
    container_name: "fund_postgres"  # 容器名称
    volumes:
      - pg_data:/var/lib/postgresql  # 数据卷挂载
    environment:
      - POSTGRES_DB=fund  # 默认数据库名
      - POSTGRES_USER=postgres  # 默认数据库用户
      - POSTGRES_PASSWORD=123456  # 默认数据库密码

  mongo:
    image: mongo
    container_name: "fund_mongo"
    volumes:
      - mongo_data:/var/lib/mongo

  redis:
    image: redis
    container_name: "fund_redis"
    volumes:
      - redis_data:/var/lib/redis

  web_go:
    container_name: "fund_go"
    build: .  # Dockerfile文件目录
    ports:  # 暴露端口
      - "10888:10888"
    links:
      - pg
      - redis
      - mongo
    depends_on:
      - pg
      - redis
      - mongo

  web_py:
    container_name: "fund_py"
    build: C:/Users/lucario/PycharmProjects/fund/  # Dockerfile文件目录
    command: python manage.py runserver 0.0.0.0:5000  # 运行容器时运行命令
    ports:
      - "5000:5000"
    links:
      - pg
      - mongo
    depends_on:
      - pg
      - mongo

volumes: # 数据卷
  pg_data: {}
  mongo_data: {}
  redis_data: {}