version: '2'
services:
  pg:
    image: postgres
    container_name: "fund_postgres"
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  mongo:
    image: mongo
    container_name: "fund_mongo"
    volumes:
      - mongo_data:/var/lib/mongo

  redis:
    image: redis
    container_name: "fund_redis"
    volumes:
      - redis_data:/var/lib/redis

  web_go:
    container_name: "fund_go"
#    restart: always
    build: .
    ports:
      - "10888:10888"
    links:
      - pg
      - redis
      - mongo
    depends_on:
      - pg
      - redis
      - mongo

#  web_py:
#    container_name: "fund_py"
#    build: C:/Users/lucario/PycharmProjects/fund/
#    command: python manage.py runserver 0.0.0.0:5000
#    restart: always
#    ports:
#      - "5000:5000"
#    links:
#      - pg
#      - mongo
#    depends_on:
#      - pg
#      - mongo

volumes: # 数据卷
  pg_data: {}
  mongo_data: {}
  redis_data: {}